# 默认的profile为dev，其他环境通过指定启动参数使用不同的profile，比如：
#   测试环境：java -jar my-spring-boot.jar --spring.profiles.active=test
#   生产环境：java -jar my-spring-boot.jar --spring.profiles.active=prod
spring:
  profiles:
    active: dev
#  cache:
#    type: CAFFEINE #指定cache类型
#    cache-names:
#      - getPersonById
#      - name2
#    caffeine:
#      spec: maximumSize=500,expireAfterWrite=5s

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 12345
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

mybatis:
  mapperLocations: classpath:mapper/xml/*.xml

server:
  port: 8082
management:
  port: 54001
  health:
    mail:
      enabled: false

---
# 开发环境配置
spring:
  profiles: dev
  redis:
    host: 59.110.169.156
    port: 6379
  datasource:
    url: jdbc:mysql://59.110.169.156:3306/bbd?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;rewriteBatchedStatements=TRUE&amp;useSSL=false&amp;serverTimezone=UTC

myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: abc
      value: abcValue
    - name: efg
      value: efgValue
  listProp2:
    - config2Value1
    - config2Vavlue2
  mapProps:
    key1: value1
    key2: value2

---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://59.110.169.156:3306/bbd?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;rewriteBatchedStatements=TRUE&amp;useSSL=false&amp;serverTimezone=UTC

---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://59.110.169.156:3306/bbd?useUnicode=true&amp;characterEncoding=utf8&amp;autoReconnect=true&amp;rewriteBatchedStatements=TRUE&amp;useSSL=false&amp;serverTimezone=UTC